eng = {
    "title": "📄 Question Paper Generator",
    "caption1": "This app in pre-beta release. We are testing more features 😎",
    "caption2": "👈 To generate set QP settings here",
    "caption3": "👇 And choose input type",
    "result": "Result",
    "gen_result": 'Here will apear your question paper text',
    "settings": "⚙️ Settings",
    "qp_type": "QP Type",
    "type_of_input": "Type of input:",
    "test": "Test",
    "n_o_t": "Number of tasks in test",
    "n_o_a": "Number of answers in task",
    "input_header": "What input do you prefer?",
    "pdf": "PDF",
    "image": "Image",
    "text": "Text",
    "choose_file": "Choose a file",
    "select_pages": "Select pages",
    "make_qp": "🖨️Make question paper",
    "doc_prep": "Document preparation...",
    "image_prep": "Image preparation...",
    "test_edit": "Test editing...",
    "done": "Done!",
    "caption_image": "Converting images to text can take a time!",
    "input_txt": "Input text",
    "paste_txt": "Paste your text here",
}

ru = {
    "title": "📄 Генератор заданий",
    "caption1": "Это приложение в pre-beta версии. Мы тестируем новые функции 😎",
    "caption2": "👈 Настройте генерацию теста здесь",
    "caption3": "👇 Выберите тип ввода здесь",
    "result": "Результат",
    "gen_result": 'Здесь появится результат генерации',
    "settings": "⚙️ Настройки",
    "qp_type": "Вид задания",
    "type_of_input": "Тип ввода:",
    "test": "Тест",
    "n_o_t": "Количество вопросов",
    "n_o_a": "Количество ответов в вопросе",
    "input_header": "Выберите тип ввода",
    "pdf": "PDF",
    "image": "Изображение",
    "text": "Текст",
    "choose_file": "Выберите файл",
    "select_pages": "Выберите страницы",
    "make_qp": "🖨️ Сделать тест",
    "doc_prep": "Подготовка документа...",
    "image_prep": "Подготовка изображения...",
    "test_edit": "Генерация теста...",
    "done": "Готово!",
    "caption_image": "Преобразование изображения может занять время!",
    "input_txt": "Введите текст",
    "paste_txt": "Скопируйте свой текст сюда",
}

languages = {"🇬🇧": eng, "🇷🇺": ru}

